/**
 * Mejora 7 (Versículo del Día) — ADR-007.
 *
 * Array estático de versículos bíblicos bilingües (365, ~un año sin repetir).
 * La selección diaria es pura (sin API ni DB): `dayOfYear % verses.length`,
 * así todos los estudiantes ven el mismo versículo el mismo día.
 *
 * Criterio de selección: versículos conocidos, denominacionalmente neutros
 * (sin doctrinas específicas ni libros deuterocanónicos), con tono de sabiduría
 * y fe activa, relevantes para jóvenes de 13–17 años. Texto en español LATAM
 * neutro (es-419): sin "vosotros", sin arcaísmos.
 */

export interface Verse {
  textEs: string;
  textEn: string;
  referenceEs: string;
  referenceEn: string;
}

const verses: Verse[] = [
  // — Génesis / Genesis —
  { textEs: 'Y vio Dios todo lo que había hecho, y era muy bueno.', textEn: 'God saw all that he had made, and it was very good.', referenceEs: 'Génesis 1:31', referenceEn: 'Genesis 1:31' },
  { textEs: 'Creó, pues, Dios al ser humano a su imagen; lo creó a imagen de Dios.', textEn: 'So God created mankind in his own image, in the image of God he created them.', referenceEs: 'Génesis 1:27', referenceEn: 'Genesis 1:27' },
  { textEs: 'El Señor te bendiga y te guarde; haga resplandecer su rostro sobre ti.', textEn: 'The Lord bless you and keep you; the Lord make his face shine on you.', referenceEs: 'Números 6:24-25', referenceEn: 'Numbers 6:24-25' },
  // — Éxodo / Exodus —
  { textEs: 'El Señor peleará por ustedes; ustedes solo tienen que mantenerse en calma.', textEn: 'The Lord will fight for you; you need only to be still.', referenceEs: 'Éxodo 14:14', referenceEn: 'Exodus 14:14' },
  { textEs: 'El Señor es mi fortaleza y mi canción; él es mi salvación.', textEn: 'The Lord is my strength and my defense; he has become my salvation.', referenceEs: 'Éxodo 15:2', referenceEn: 'Exodus 15:2' },
  // — Deuteronomio / Deuteronomy —
  { textEs: 'Ama al Señor tu Dios con todo tu corazón, con toda tu alma y con todas tus fuerzas.', textEn: 'Love the Lord your God with all your heart and with all your soul and with all your strength.', referenceEs: 'Deuteronomio 6:5', referenceEn: 'Deuteronomy 6:5' },
  { textEs: 'Sean fuertes y valientes. No teman ni se asusten, porque el Señor su Dios siempre los acompañará.', textEn: 'Be strong and courageous. Do not be afraid, for the Lord your God goes with you.', referenceEs: 'Deuteronomio 31:6', referenceEn: 'Deuteronomy 31:6' },
  { textEs: 'El Señor mismo marcha al frente de ti y estará contigo; nunca te dejará ni te abandonará.', textEn: 'The Lord himself goes before you and will be with you; he will never leave you nor forsake you.', referenceEs: 'Deuteronomio 31:8', referenceEn: 'Deuteronomy 31:8' },
  // — Josué / Joshua —
  { textEs: 'Esfuérzate y sé valiente; no temas ni desmayes, porque el Señor tu Dios estará contigo dondequiera que vayas.', textEn: 'Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go.', referenceEs: 'Josué 1:9', referenceEn: 'Joshua 1:9' },
  { textEs: 'Pero yo y mi familia serviremos al Señor.', textEn: 'But as for me and my household, we will serve the Lord.', referenceEs: 'Josué 24:15', referenceEn: 'Joshua 24:15' },
  // — 1 Samuel —
  { textEs: 'La gente se fija en las apariencias, pero el Señor mira el corazón.', textEn: 'People look at the outward appearance, but the Lord looks at the heart.', referenceEs: '1 Samuel 16:7', referenceEn: '1 Samuel 16:7' },
  { textEs: 'La batalla es del Señor.', textEn: 'The battle is the Lord’s.', referenceEs: '1 Samuel 17:47', referenceEn: '1 Samuel 17:47' },
  // — 1 Crónicas / 1 Chronicles —
  { textEs: 'Tuyos son, Señor, la grandeza y el poder, la gloria, la victoria y la majestad.', textEn: 'Yours, Lord, is the greatness and the power and the glory and the majesty and the splendor.', referenceEs: '1 Crónicas 29:11', referenceEn: '1 Chronicles 29:11' },
  // — Nehemías / Nehemiah —
  { textEs: 'No estén tristes, pues el gozo del Señor es nuestra fortaleza.', textEn: 'Do not grieve, for the joy of the Lord is your strength.', referenceEs: 'Nehemías 8:10', referenceEn: 'Nehemiah 8:10' },
  // — Job —
  { textEs: 'Yo sé que mi redentor vive.', textEn: 'I know that my redeemer lives.', referenceEs: 'Job 19:25', referenceEn: 'Job 19:25' },
  { textEs: 'Él conoce mi camino; si me examina, saldré como el oro.', textEn: 'He knows the way that I take; when he has tested me, I will come forth as gold.', referenceEs: 'Job 23:10', referenceEn: 'Job 23:10' },
  // — Salmos / Psalms —
  { textEs: 'Dichoso el que se deleita en la ley del Señor, y en ella medita de día y de noche.', textEn: 'Blessed is the one whose delight is in the law of the Lord, and who meditates on it day and night.', referenceEs: 'Salmo 1:2', referenceEn: 'Psalm 1:2' },
  { textEs: 'En paz me acuesto y me duermo, porque solo tú, Señor, me haces vivir confiado.', textEn: 'In peace I will lie down and sleep, for you alone, Lord, make me dwell in safety.', referenceEs: 'Salmo 4:8', referenceEn: 'Psalm 4:8' },
  { textEs: '¿Qué es el ser humano para que en él pienses, el hijo del hombre para que lo cuides?', textEn: 'What is mankind that you are mindful of them, human beings that you care for them?', referenceEs: 'Salmo 8:4', referenceEn: 'Psalm 8:4' },
  { textEs: 'Los que conocen tu nombre confían en ti, porque tú, Señor, jamás abandonas a los que te buscan.', textEn: 'Those who know your name trust in you, for you, Lord, have never forsaken those who seek you.', referenceEs: 'Salmo 9:10', referenceEn: 'Psalm 9:10' },
  { textEs: 'El Señor es mi roca, mi amparo, mi libertador.', textEn: 'The Lord is my rock, my fortress and my deliverer.', referenceEs: 'Salmo 18:2', referenceEn: 'Psalm 18:2' },
  { textEs: 'Los cielos cuentan la gloria de Dios, el firmamento proclama la obra de sus manos.', textEn: 'The heavens declare the glory of God; the skies proclaim the work of his hands.', referenceEs: 'Salmo 19:1', referenceEn: 'Psalm 19:1' },
  { textEs: 'Que sean de tu agrado las palabras de mi boca y la meditación de mi corazón.', textEn: 'May these words of my mouth and this meditation of my heart be pleasing in your sight.', referenceEs: 'Salmo 19:14', referenceEn: 'Psalm 19:14' },
  { textEs: 'El Señor es mi pastor; nada me faltará.', textEn: 'The Lord is my shepherd, I lack nothing.', referenceEs: 'Salmo 23:1', referenceEn: 'Psalm 23:1' },
  { textEs: 'Aunque ande en valle de sombra de muerte, no temeré mal alguno, porque tú estás conmigo.', textEn: 'Even though I walk through the darkest valley, I will fear no evil, for you are with me.', referenceEs: 'Salmo 23:4', referenceEn: 'Psalm 23:4' },
  { textEs: 'El Señor es mi luz y mi salvación; ¿a quién temeré?', textEn: 'The Lord is my light and my salvation—whom shall I fear?', referenceEs: 'Salmo 27:1', referenceEn: 'Psalm 27:1' },
  { textEs: 'Espera en el Señor; ten valor, cobra ánimo y espera en el Señor.', textEn: 'Wait for the Lord; be strong and take heart and wait for the Lord.', referenceEs: 'Salmo 27:14', referenceEn: 'Psalm 27:14' },
  { textEs: 'El Señor es mi fuerza y mi escudo; mi corazón en él confía.', textEn: 'The Lord is my strength and my shield; my heart trusts in him.', referenceEs: 'Salmo 28:7', referenceEn: 'Psalm 28:7' },
  { textEs: 'El llanto puede durar toda la noche, pero con la mañana llega la alegría.', textEn: 'Weeping may stay for the night, but rejoicing comes in the morning.', referenceEs: 'Salmo 30:5', referenceEn: 'Psalm 30:5' },
  { textEs: 'Sean fuertes y cobren ánimo, todos los que esperan en el Señor.', textEn: 'Be strong and take heart, all you who hope in the Lord.', referenceEs: 'Salmo 31:24', referenceEn: 'Psalm 31:24' },
  { textEs: 'Yo te instruiré, te mostraré el camino que debes seguir; yo te guiaré y velaré por ti.', textEn: 'I will instruct you and teach you in the way you should go; I will counsel you with my loving eye on you.', referenceEs: 'Salmo 32:8', referenceEn: 'Psalm 32:8' },
  { textEs: 'Prueben y vean que el Señor es bueno; dichoso el que en él se refugia.', textEn: 'Taste and see that the Lord is good; blessed is the one who takes refuge in him.', referenceEs: 'Salmo 34:8', referenceEn: 'Psalm 34:8' },
  { textEs: 'El Señor está cerca de los quebrantados de corazón.', textEn: 'The Lord is close to the brokenhearted.', referenceEs: 'Salmo 34:18', referenceEn: 'Psalm 34:18' },
  { textEs: 'Deléitate en el Señor, y él te concederá los deseos de tu corazón.', textEn: 'Take delight in the Lord, and he will give you the desires of your heart.', referenceEs: 'Salmo 37:4', referenceEn: 'Psalm 37:4' },
  { textEs: 'Encomienda al Señor tu camino; confía en él, y él actuará.', textEn: 'Commit your way to the Lord; trust in him and he will do this.', referenceEs: 'Salmo 37:5', referenceEn: 'Psalm 37:5' },
  { textEs: 'Como el ciervo anhela las corrientes de agua, así te anhela a ti, oh Dios, mi alma.', textEn: 'As the deer pants for streams of water, so my soul pants for you, my God.', referenceEs: 'Salmo 42:1', referenceEn: 'Psalm 42:1' },
  { textEs: 'Dios es nuestro amparo y fortaleza, nuestra ayuda segura en momentos de angustia.', textEn: 'God is our refuge and strength, an ever-present help in trouble.', referenceEs: 'Salmo 46:1', referenceEn: 'Psalm 46:1' },
  { textEs: 'Quédense quietos y reconozcan que yo soy Dios.', textEn: 'Be still, and know that I am God.', referenceEs: 'Salmo 46:10', referenceEn: 'Psalm 46:10' },
  { textEs: 'Crea en mí, oh Dios, un corazón limpio, y renueva la firmeza de mi espíritu.', textEn: 'Create in me a pure heart, O God, and renew a steadfast spirit within me.', referenceEs: 'Salmo 51:10', referenceEn: 'Psalm 51:10' },
  { textEs: 'Encomienda al Señor tus cargas, y él te sostendrá.', textEn: 'Cast your cares on the Lord and he will sustain you.', referenceEs: 'Salmo 55:22', referenceEn: 'Psalm 55:22' },
  { textEs: 'Cuando siento miedo, pongo en ti mi confianza.', textEn: 'When I am afraid, I put my trust in you.', referenceEs: 'Salmo 56:3', referenceEn: 'Psalm 56:3' },
  { textEs: 'Confíen en él en todo momento; ábranle su corazón, porque Dios es nuestro refugio.', textEn: 'Trust in him at all times; pour out your hearts to him, for God is our refuge.', referenceEs: 'Salmo 62:8', referenceEn: 'Psalm 62:8' },
  { textEs: 'Mi cuerpo y mi corazón pueden desfallecer, pero Dios es la fuerza de mi corazón.', textEn: 'My flesh and my heart may fail, but God is the strength of my heart.', referenceEs: 'Salmo 73:26', referenceEn: 'Psalm 73:26' },
  { textEs: 'El Señor es sol y escudo; gracia y gloria otorga el Señor.', textEn: 'For the Lord God is a sun and shield; the Lord bestows favor and honor.', referenceEs: 'Salmo 84:11', referenceEn: 'Psalm 84:11' },
  { textEs: 'Tú, Señor, eres bueno y perdonador; grande es tu amor por todos los que te invocan.', textEn: 'You, Lord, are forgiving and good, abounding in love to all who call to you.', referenceEs: 'Salmo 86:5', referenceEn: 'Psalm 86:5' },
  { textEs: 'Enséñanos a contar bien nuestros días, para que nuestro corazón adquiera sabiduría.', textEn: 'Teach us to number our days, that we may gain a heart of wisdom.', referenceEs: 'Salmo 90:12', referenceEn: 'Psalm 90:12' },
  { textEs: 'El que habita al abrigo del Altísimo descansará a la sombra del Todopoderoso.', textEn: 'Whoever dwells in the shelter of the Most High will rest in the shadow of the Almighty.', referenceEs: 'Salmo 91:1', referenceEn: 'Psalm 91:1' },
  { textEs: 'Cuando en mí la angustia iba en aumento, tu consuelo llenaba mi alma de alegría.', textEn: 'When anxiety was great within me, your consolation brought me joy.', referenceEs: 'Salmo 94:19', referenceEn: 'Psalm 94:19' },
  { textEs: 'Adoren al Señor con regocijo. Preséntense ante él con cánticos de júbilo.', textEn: 'Worship the Lord with gladness; come before him with joyful songs.', referenceEs: 'Salmo 100:2', referenceEn: 'Psalm 100:2' },
  { textEs: 'Den gracias al Señor, porque él es bueno; su gran amor perdura para siempre.', textEn: 'Give thanks to the Lord, for he is good; his love endures forever.', referenceEs: 'Salmo 107:1', referenceEn: 'Psalm 107:1' },
  { textEs: 'El Señor está conmigo; no tengo miedo. ¿Qué me puede hacer un simple mortal?', textEn: 'The Lord is with me; I will not be afraid. What can mere mortals do to me?', referenceEs: 'Salmo 118:6', referenceEn: 'Psalm 118:6' },
  { textEs: 'Este es el día que hizo el Señor; regocijémonos y alegrémonos en él.', textEn: 'The Lord has done it this very day; let us rejoice today and be glad.', referenceEs: 'Salmo 118:24', referenceEn: 'Psalm 118:24' },
  { textEs: 'En mi corazón atesoro tus palabras para no pecar contra ti.', textEn: 'I have hidden your word in my heart that I might not sin against you.', referenceEs: 'Salmo 119:11', referenceEn: 'Psalm 119:11' },
  { textEs: 'Lámpara es a mis pies tu palabra, y luz para mi camino.', textEn: 'Your word is a lamp for my feet, a light on my path.', referenceEs: 'Salmo 119:105', referenceEn: 'Psalm 119:105' },
  { textEs: 'A las montañas levanto mis ojos; ¿de dónde ha de venir mi ayuda? Mi ayuda proviene del Señor.', textEn: 'I lift up my eyes to the mountains—where does my help come from? My help comes from the Lord.', referenceEs: 'Salmo 121:1-2', referenceEn: 'Psalm 121:1-2' },
  { textEs: 'El Señor te protegerá; de todo mal protegerá tu vida.', textEn: 'The Lord will keep you from all harm—he will watch over your life.', referenceEs: 'Salmo 121:7', referenceEn: 'Psalm 121:7' },
  { textEs: 'Los que siembran con lágrimas, con cantos de alegría cosecharán.', textEn: 'Those who sow with tears will reap with songs of joy.', referenceEs: 'Salmo 126:5', referenceEn: 'Psalm 126:5' },
  { textEs: 'Si el Señor no edifica la casa, en vano se esfuerzan los que la construyen.', textEn: 'Unless the Lord builds the house, the builders labor in vain.', referenceEs: 'Salmo 127:1', referenceEn: 'Psalm 127:1' },
  { textEs: '¡Cuán bueno y agradable es que los hermanos convivan en armonía!', textEn: 'How good and pleasant it is when God’s people live together in unity!', referenceEs: 'Salmo 133:1', referenceEn: 'Psalm 133:1' },
  { textEs: 'Te alabo porque soy una creación admirable. ¡Tus obras son maravillosas!', textEn: 'I praise you because I am fearfully and wonderfully made; your works are wonderful.', referenceEs: 'Salmo 139:14', referenceEn: 'Psalm 139:14' },
  { textEs: 'Examíname, oh Dios, y conoce mi corazón; ponme a prueba y conoce mis pensamientos.', textEn: 'Search me, God, and know my heart; test me and know my anxious thoughts.', referenceEs: 'Salmo 139:23', referenceEn: 'Psalm 139:23' },
  { textEs: 'Por la mañana hazme saber de tu gran amor, porque en ti he puesto mi confianza.', textEn: 'Let the morning bring me word of your unfailing love, for I have put my trust in you.', referenceEs: 'Salmo 143:8', referenceEn: 'Psalm 143:8' },
  { textEs: 'El Señor está cerca de quienes lo invocan, de quienes lo invocan de corazón.', textEn: 'The Lord is near to all who call on him, to all who call on him in truth.', referenceEs: 'Salmo 145:18', referenceEn: 'Psalm 145:18' },
  { textEs: 'Él sana a los de corazón quebrantado y venda sus heridas.', textEn: 'He heals the brokenhearted and binds up their wounds.', referenceEs: 'Salmo 147:3', referenceEn: 'Psalm 147:3' },
  { textEs: '¡Que todo lo que respira alabe al Señor!', textEn: 'Let everything that has breath praise the Lord.', referenceEs: 'Salmo 150:6', referenceEn: 'Psalm 150:6' },
  // — Proverbios / Proverbs —
  { textEs: 'El temor del Señor es el principio del conocimiento.', textEn: 'The fear of the Lord is the beginning of knowledge.', referenceEs: 'Proverbios 1:7', referenceEn: 'Proverbs 1:7' },
  { textEs: 'Porque el Señor da la sabiduría; conocimiento y ciencia brotan de sus labios.', textEn: 'For the Lord gives wisdom; from his mouth come knowledge and understanding.', referenceEs: 'Proverbios 2:6', referenceEn: 'Proverbs 2:6' },
  { textEs: 'Confía en el Señor con todo tu corazón, y no te apoyes en tu propio entendimiento.', textEn: 'Trust in the Lord with all your heart and lean not on your own understanding.', referenceEs: 'Proverbios 3:5', referenceEn: 'Proverbs 3:5' },
  { textEs: 'Reconócelo en todos tus caminos, y él allanará tus sendas.', textEn: 'In all your ways submit to him, and he will make your paths straight.', referenceEs: 'Proverbios 3:6', referenceEn: 'Proverbs 3:6' },
  { textEs: 'Por sobre todas las cosas cuida tu corazón, porque de él mana la vida.', textEn: 'Above all else, guard your heart, for everything you do flows from it.', referenceEs: 'Proverbios 4:23', referenceEn: 'Proverbs 4:23' },
  { textEs: 'El que ama la disciplina ama el conocimiento; el que la aborrece es un necio.', textEn: 'Whoever loves discipline loves knowledge, but whoever hates correction is stupid.', referenceEs: 'Proverbios 12:1', referenceEn: 'Proverbs 12:1' },
  { textEs: 'El que anda con sabios, sabio se vuelve; el que anda con necios sale mal parado.', textEn: 'Walk with the wise and become wise, for a companion of fools suffers harm.', referenceEs: 'Proverbios 13:20', referenceEn: 'Proverbs 13:20' },
  { textEs: 'La respuesta amable calma el enojo, pero la palabra hiriente lo enciende.', textEn: 'A gentle answer turns away wrath, but a harsh word stirs up anger.', referenceEs: 'Proverbios 15:1', referenceEn: 'Proverbs 15:1' },
  { textEs: 'Encomienda al Señor tus obras, y tus proyectos se cumplirán.', textEn: 'Commit to the Lord whatever you do, and he will establish your plans.', referenceEs: 'Proverbios 16:3', referenceEn: 'Proverbs 16:3' },
  { textEs: 'El corazón del hombre traza su rumbo, pero los pasos los dirige el Señor.', textEn: 'In their hearts humans plan their course, but the Lord establishes their steps.', referenceEs: 'Proverbios 16:9', referenceEn: 'Proverbs 16:9' },
  { textEs: 'El nombre del Señor es una torre poderosa; a ella corren los justos y se ponen a salvo.', textEn: 'The name of the Lord is a fortified tower; the righteous run to it and are safe.', referenceEs: 'Proverbios 18:10', referenceEn: 'Proverbs 18:10' },
  { textEs: 'Atiende al consejo y acepta la corrección, y llegarás a ser sabio.', textEn: 'Listen to advice and accept discipline, and at the end you will be counted among the wise.', referenceEs: 'Proverbios 19:20', referenceEn: 'Proverbs 19:20' },
  { textEs: 'El hierro se afila con el hierro, y el hombre en el trato con el hombre.', textEn: 'As iron sharpens iron, so one person sharpens another.', referenceEs: 'Proverbios 27:17', referenceEn: 'Proverbs 27:17' },
  { textEs: 'Instruye al niño en el camino correcto, y aun en su vejez no lo abandonará.', textEn: 'Start children off on the way they should go, and even when they are old they will not turn from it.', referenceEs: 'Proverbios 22:6', referenceEn: 'Proverbs 22:6' },
  { textEs: 'La mujer que teme al Señor es digna de alabanza.', textEn: 'A woman who fears the Lord is to be praised.', referenceEs: 'Proverbios 31:30', referenceEn: 'Proverbs 31:30' },
  { textEs: 'El corazón alegre es una buena medicina, pero el ánimo decaído seca los huesos.', textEn: 'A cheerful heart is good medicine, but a crushed spirit dries up the bones.', referenceEs: 'Proverbios 17:22', referenceEn: 'Proverbs 17:22' },
  { textEs: 'El que halla esposa halla la felicidad; recibe el favor del Señor.', textEn: 'He who finds a wife finds what is good and receives favor from the Lord.', referenceEs: 'Proverbios 18:22', referenceEn: 'Proverbs 18:22' },
  { textEs: 'Mejor es la sabiduría que las piedras preciosas; ¡nada de lo que desees se le compara!', textEn: 'Wisdom is more precious than rubies, and nothing you desire can compare with her.', referenceEs: 'Proverbios 8:11', referenceEn: 'Proverbs 8:11' },
  { textEs: 'El corazón alegre se refleja en el rostro.', textEn: 'A happy heart makes the face cheerful.', referenceEs: 'Proverbios 15:13', referenceEn: 'Proverbs 15:13' },
  { textEs: 'Las palabras amables son como un panal de miel: endulzan la vida y dan salud al cuerpo.', textEn: 'Gracious words are a honeycomb, sweet to the soul and healing to the bones.', referenceEs: 'Proverbios 16:24', referenceEn: 'Proverbs 16:24' },
  { textEs: 'El que adquiere cordura a sí mismo se ama, y el que retiene el discernimiento prospera.', textEn: 'The one who gets wisdom loves life; the one who cherishes understanding will soon prosper.', referenceEs: 'Proverbios 19:8', referenceEn: 'Proverbs 19:8' },
  { textEs: 'El que cuida su boca y su lengua se libra de muchas angustias.', textEn: 'Those who guard their mouths and their tongues keep themselves from calamity.', referenceEs: 'Proverbios 21:23', referenceEn: 'Proverbs 21:23' },
  { textEs: 'Vale más el buen nombre que las muchas riquezas.', textEn: 'A good name is more desirable than great riches.', referenceEs: 'Proverbios 22:1', referenceEn: 'Proverbs 22:1' },
  { textEs: 'No te jactes del día de mañana, porque no sabes lo que el día traerá.', textEn: 'Do not boast about tomorrow, for you do not know what a day may bring.', referenceEs: 'Proverbios 27:1', referenceEn: 'Proverbs 27:1' },
  { textEs: 'El justo vive confiado como un león.', textEn: 'The righteous are as bold as a lion.', referenceEs: 'Proverbios 28:1', referenceEn: 'Proverbs 28:1' },
  { textEs: 'Toda palabra de Dios es digna de crédito; Dios protege a los que en él confían.', textEn: 'Every word of God is flawless; he is a shield to those who take refuge in him.', referenceEs: 'Proverbios 30:5', referenceEn: 'Proverbs 30:5' },
  { textEs: 'El que confía en sí mismo es un necio; el que actúa con sabiduría se pone a salvo.', textEn: 'Those who trust in themselves are fools, but those who walk in wisdom are kept safe.', referenceEs: 'Proverbios 28:26', referenceEn: 'Proverbs 28:26' },
  { textEs: 'Abre la boca en favor de los que no tienen voz.', textEn: 'Speak up for those who cannot speak for themselves.', referenceEs: 'Proverbios 31:8', referenceEn: 'Proverbs 31:8' },
  { textEs: 'El temor al hombre resulta una trampa, pero el que confía en el Señor sale bien librado.', textEn: 'Fear of man will prove to be a snare, but whoever trusts in the Lord is kept safe.', referenceEs: 'Proverbios 29:25', referenceEn: 'Proverbs 29:25' },
  { textEs: 'Como el agua refleja el rostro, así el corazón refleja a la persona.', textEn: 'As water reflects the face, so one’s life reflects the heart.', referenceEs: 'Proverbios 27:19', referenceEn: 'Proverbs 27:19' },
  { textEs: 'El que es generoso prospera; el que reanima será reanimado.', textEn: 'A generous person will prosper; whoever refreshes others will be refreshed.', referenceEs: 'Proverbios 11:25', referenceEn: 'Proverbs 11:25' },
  { textEs: 'La esperanza frustrada aflige al corazón; el deseo cumplido es un árbol de vida.', textEn: 'Hope deferred makes the heart sick, but a longing fulfilled is a tree of life.', referenceEs: 'Proverbios 13:12', referenceEn: 'Proverbs 13:12' },
  { textEs: 'El que es paciente muestra gran discernimiento; el que es agresivo muestra mucha insensatez.', textEn: 'Whoever is patient has great understanding, but one who is quick-tempered displays folly.', referenceEs: 'Proverbios 14:29', referenceEn: 'Proverbs 14:29' },
  { textEs: 'El Señor está lejos de los malvados, pero escucha las oraciones de los justos.', textEn: 'The Lord is far from the wicked, but he hears the prayer of the righteous.', referenceEs: 'Proverbios 15:29', referenceEn: 'Proverbs 15:29' },
  { textEs: 'Mejor es ser humilde de espíritu entre los pobres que repartir despojos entre los soberbios.', textEn: 'Better to be lowly in spirit along with the oppressed than to share plunder with the proud.', referenceEs: 'Proverbios 16:19', referenceEn: 'Proverbs 16:19' },
  { textEs: 'El crisol prueba la plata y el horno prueba el oro, pero el Señor prueba los corazones.', textEn: 'The crucible for silver and the furnace for gold, but the Lord tests the heart.', referenceEs: 'Proverbios 17:3', referenceEn: 'Proverbs 17:3' },
  { textEs: 'En el corazón del hombre hay muchos planes, pero el propósito del Señor prevalecerá.', textEn: 'Many are the plans in a person’s heart, but it is the Lord’s purpose that prevails.', referenceEs: 'Proverbios 19:21', referenceEn: 'Proverbs 19:21' },
  { textEs: 'Hasta a los niños se les conoce por sus hechos: si su conducta es pura y recta.', textEn: 'Even small children are known by their actions, so is their conduct really pure and upright?', referenceEs: 'Proverbios 20:11', referenceEn: 'Proverbs 20:11' },
  { textEs: 'El que persigue la justicia y el amor halla vida, prosperidad y honra.', textEn: 'Whoever pursues righteousness and love finds life, prosperity and honor.', referenceEs: 'Proverbios 21:21', referenceEn: 'Proverbs 21:21' },
  { textEs: 'Como una manzana de oro con incrustaciones de plata es la palabra dicha a tiempo.', textEn: 'Like apples of gold in settings of silver is a ruling rightly given.', referenceEs: 'Proverbios 25:11', referenceEn: 'Proverbs 25:11' },
  { textEs: 'No respondas al necio según su necedad, para no ser tú también como él.', textEn: 'Do not answer a fool according to his folly, or you yourself will be just like him.', referenceEs: 'Proverbios 26:4', referenceEn: 'Proverbs 26:4' },
  { textEs: 'El que confiesa sus pecados y los abandona halla misericordia.', textEn: 'Whoever conceals their sins does not prosper, but the one who confesses and renounces them finds mercy.', referenceEs: 'Proverbios 28:13', referenceEn: 'Proverbs 28:13' },
  { textEs: 'Quien se conduce con integridad anda seguro.', textEn: 'Whoever walks in integrity walks securely.', referenceEs: 'Proverbios 10:9', referenceEn: 'Proverbs 10:9' },
  { textEs: 'El sabio teme al Señor y se aparta del mal.', textEn: 'The wise fear the Lord and shun evil.', referenceEs: 'Proverbios 14:16', referenceEn: 'Proverbs 14:16' },
  { textEs: 'Con la humildad viene la sabiduría.', textEn: 'But with humility comes wisdom.', referenceEs: 'Proverbios 11:2', referenceEn: 'Proverbs 11:2' },
  // — Eclesiastés / Ecclesiastes —
  { textEs: 'Todo tiene su momento oportuno; hay un tiempo para todo lo que se hace bajo el cielo.', textEn: 'There is a time for everything, and a season for every activity under the heavens.', referenceEs: 'Eclesiastés 3:1', referenceEn: 'Ecclesiastes 3:1' },
  { textEs: 'Dios hizo todo hermoso en su momento.', textEn: 'He has made everything beautiful in its time.', referenceEs: 'Eclesiastés 3:11', referenceEn: 'Ecclesiastes 3:11' },
  { textEs: 'Más valen dos que uno, porque obtienen más fruto de su esfuerzo.', textEn: 'Two are better than one, because they have a good return for their labor.', referenceEs: 'Eclesiastés 4:9', referenceEn: 'Ecclesiastes 4:9' },
  { textEs: 'Acuérdate de tu Creador en los días de tu juventud.', textEn: 'Remember your Creator in the days of your youth.', referenceEs: 'Eclesiastés 12:1', referenceEn: 'Ecclesiastes 12:1' },
  { textEs: 'Teme a Dios y cumple sus mandamientos, porque esto es todo para el ser humano.', textEn: 'Fear God and keep his commandments, for this is the duty of all mankind.', referenceEs: 'Eclesiastés 12:13', referenceEn: 'Ecclesiastes 12:13' },
  // — Isaías / Isaiah —
  { textEs: 'Aquí estoy. Envíame a mí.', textEn: 'Here am I. Send me!', referenceEs: 'Isaías 6:8', referenceEn: 'Isaiah 6:8' },
  { textEs: 'Porque nos ha nacido un niño, se nos ha dado un hijo; y se llamará Príncipe de paz.', textEn: 'For to us a child is born, to us a son is given; and he will be called Prince of Peace.', referenceEs: 'Isaías 9:6', referenceEn: 'Isaiah 9:6' },
  { textEs: 'Yo confiaré y no temeré, porque mi fuerza y mi canción es el Señor.', textEn: 'I will trust and not be afraid. The Lord is my strength and my defense.', referenceEs: 'Isaías 12:2', referenceEn: 'Isaiah 12:2' },
  { textEs: 'Al de carácter firme lo guardas en perfecta paz, porque en ti confía.', textEn: 'You will keep in perfect peace those whose minds are steadfast, because they trust in you.', referenceEs: 'Isaías 26:3', referenceEn: 'Isaiah 26:3' },
  { textEs: 'Confíen en el Señor para siempre, porque el Señor es la Roca eterna.', textEn: 'Trust in the Lord forever, for the Lord, the Lord himself, is the Rock eternal.', referenceEs: 'Isaías 26:4', referenceEn: 'Isaiah 26:4' },
  { textEs: 'No temas, porque yo estoy contigo; no te angusties, porque yo soy tu Dios. Te fortaleceré y te ayudaré.', textEn: 'So do not fear, for I am with you; do not be dismayed, for I am your God. I will strengthen you and help you.', referenceEs: 'Isaías 41:10', referenceEn: 'Isaiah 41:10' },
  { textEs: 'Cuando pases por las aguas, yo estaré contigo; y cuando cruces los ríos, no te cubrirán.', textEn: 'When you pass through the waters, I will be with you; and when you pass through the rivers, they will not sweep over you.', referenceEs: 'Isaías 43:2', referenceEn: 'Isaiah 43:2' },
  { textEs: 'Yo soy el que borra tus transgresiones por amor a mí mismo.', textEn: 'I, even I, am he who blots out your transgressions, for my own sake.', referenceEs: 'Isaías 43:25', referenceEn: 'Isaiah 43:25' },
  { textEs: 'Hasta la vejez yo seré el mismo; yo los sostendré.', textEn: 'Even to your old age and gray hairs I am he, I am he who will sustain you.', referenceEs: 'Isaías 46:4', referenceEn: 'Isaiah 46:4' },
  { textEs: 'Aunque una madre olvide a su hijo, yo no te olvidaré.', textEn: 'Though she may forget, I will not forget you!', referenceEs: 'Isaías 49:15', referenceEn: 'Isaiah 49:15' },
  { textEs: 'La hierba se seca y la flor se marchita, pero la palabra de nuestro Dios permanece para siempre.', textEn: 'The grass withers and the flowers fall, but the word of our God endures forever.', referenceEs: 'Isaías 40:8', referenceEn: 'Isaiah 40:8' },
  { textEs: 'Los que esperan en el Señor renovarán sus fuerzas; levantarán el vuelo como las águilas.', textEn: 'Those who hope in the Lord will renew their strength. They will soar on wings like eagles.', referenceEs: 'Isaías 40:31', referenceEn: 'Isaiah 40:31' },
  { textEs: 'Yo soy el Señor tu Dios, que te sostiene de tu mano derecha y te dice: No temas, yo te ayudaré.', textEn: 'For I am the Lord your God who takes hold of your right hand and says to you, Do not fear; I will help you.', referenceEs: 'Isaías 41:13', referenceEn: 'Isaiah 41:13' },
  { textEs: 'Olviden las cosas de antaño; yo voy a hacer algo nuevo.', textEn: 'Forget the former things; see, I am doing a new thing!', referenceEs: 'Isaías 43:18-19', referenceEn: 'Isaiah 43:18-19' },
  { textEs: '¡Qué hermosos son los pies de los que anuncian buenas noticias!', textEn: 'How beautiful are the feet of those who bring good news!', referenceEs: 'Isaías 52:7', referenceEn: 'Isaiah 52:7' },
  { textEs: 'Mis pensamientos no son los de ustedes, ni sus caminos son los míos, afirma el Señor.', textEn: 'For my thoughts are not your thoughts, neither are your ways my ways, declares the Lord.', referenceEs: 'Isaías 55:8', referenceEn: 'Isaiah 55:8' },
  { textEs: 'Busquen al Señor mientras se deje encontrar, llámenlo mientras esté cercano.', textEn: 'Seek the Lord while he may be found; call on him while he is near.', referenceEs: 'Isaías 55:6', referenceEn: 'Isaiah 55:6' },
  { textEs: 'Levántate y resplandece, porque ha llegado tu luz.', textEn: 'Arise, shine, for your light has come.', referenceEs: 'Isaías 60:1', referenceEn: 'Isaiah 60:1' },
  { textEs: 'El Espíritu del Señor está sobre mí, porque me ha ungido para anunciar buenas noticias a los pobres.', textEn: 'The Spirit of the Sovereign Lord is on me, because the Lord has anointed me to proclaim good news to the poor.', referenceEs: 'Isaías 61:1', referenceEn: 'Isaiah 61:1' },
  { textEs: 'Tú, Señor, eres nuestro Padre; nosotros somos el barro, y tú el alfarero.', textEn: 'You, Lord, are our Father. We are the clay, you are the potter.', referenceEs: 'Isaías 64:8', referenceEn: 'Isaiah 64:8' },
  // — Jeremías / Jeremiah —
  { textEs: 'Antes de formarte en el vientre, ya te conocía.', textEn: 'Before I formed you in the womb I knew you.', referenceEs: 'Jeremías 1:5', referenceEn: 'Jeremiah 1:5' },
  { textEs: 'Porque yo sé los planes que tengo para ustedes: planes de bienestar, para darles un futuro y una esperanza.', textEn: 'For I know the plans I have for you, plans to give you hope and a future.', referenceEs: 'Jeremías 29:11', referenceEn: 'Jeremiah 29:11' },
  { textEs: 'Me buscarán y me encontrarán cuando me busquen de todo corazón.', textEn: 'You will seek me and find me when you seek me with all your heart.', referenceEs: 'Jeremías 29:13', referenceEn: 'Jeremiah 29:13' },
  { textEs: 'Con amor eterno te he amado; por eso te sigo con fidelidad.', textEn: 'I have loved you with an everlasting love; I have drawn you with unfailing kindness.', referenceEs: 'Jeremías 31:3', referenceEn: 'Jeremiah 31:3' },
  { textEs: 'Yo soy el Señor, Dios de toda la humanidad. ¿Hay algo imposible para mí?', textEn: 'I am the Lord, the God of all mankind. Is anything too hard for me?', referenceEs: 'Jeremías 32:27', referenceEn: 'Jeremiah 32:27' },
  // — Lamentaciones / Lamentations —
  { textEs: 'El gran amor del Señor nunca se acaba, y su compasión jamás se agota. Cada mañana se renuevan.', textEn: 'Because of the Lord’s great love we are not consumed, for his compassions never fail. They are new every morning.', referenceEs: 'Lamentaciones 3:22-23', referenceEn: 'Lamentations 3:22-23' },
  { textEs: 'Bueno es el Señor con quienes en él confían, con todos los que lo buscan.', textEn: 'The Lord is good to those whose hope is in him, to the one who seeks him.', referenceEs: 'Lamentaciones 3:25', referenceEn: 'Lamentations 3:25' },
  // — Daniel —
  { textEs: 'Los que son sabios resplandecerán como el fulgor del cielo.', textEn: 'Those who are wise will shine like the brightness of the heavens.', referenceEs: 'Daniel 12:3', referenceEn: 'Daniel 12:3' },
  { textEs: 'Nuestro Dios al que servimos puede librarnos.', textEn: 'The God we serve is able to deliver us.', referenceEs: 'Daniel 3:17', referenceEn: 'Daniel 3:17' },
  // — Profetas menores / Minor Prophets —
  { textEs: 'Volvámonos al Señor. Él nos ha desgarrado, pero nos sanará.', textEn: 'Let us return to the Lord. He has torn us to pieces but he will heal us.', referenceEs: 'Oseas 6:1', referenceEn: 'Hosea 6:1' },
  { textEs: 'Todo el que invoque el nombre del Señor será salvo.', textEn: 'Everyone who calls on the name of the Lord will be saved.', referenceEs: 'Joel 2:32', referenceEn: 'Joel 2:32' },
  { textEs: 'Busquen el bien y no el mal, y vivirán.', textEn: 'Seek good, not evil, that you may live.', referenceEs: 'Amós 5:14', referenceEn: 'Amos 5:14' },
  { textEs: 'Practicar la justicia, amar la misericordia y caminar humildemente con tu Dios.', textEn: 'To act justly and to love mercy and to walk humbly with your God.', referenceEs: 'Miqueas 6:8', referenceEn: 'Micah 6:8' },
  { textEs: 'Bueno es el Señor; es refugio en el día de la angustia, y conoce a los que en él confían.', textEn: 'The Lord is good, a refuge in times of trouble. He cares for those who trust in him.', referenceEs: 'Nahúm 1:7', referenceEn: 'Nahum 1:7' },
  { textEs: 'Aunque la higuera no florezca, yo me alegraré en el Señor, me regocijaré en Dios mi Salvador.', textEn: 'Though the fig tree does not bud, yet I will rejoice in the Lord, I will be joyful in God my Savior.', referenceEs: 'Habacuc 3:17-18', referenceEn: 'Habakkuk 3:17-18' },
  { textEs: 'El Señor tu Dios está en medio de ti, y se deleita en ti con cánticos.', textEn: 'The Lord your God is with you; he will rejoice over you with singing.', referenceEs: 'Sofonías 3:17', referenceEn: 'Zephaniah 3:17' },
  { textEs: 'No es con ejército, ni con fuerza, sino con mi Espíritu, dice el Señor.', textEn: 'Not by might nor by power, but by my Spirit, says the Lord.', referenceEs: 'Zacarías 4:6', referenceEn: 'Zechariah 4:6' },
  { textEs: 'Vuélvanse a mí, y yo me volveré a ustedes, dice el Señor.', textEn: 'Return to me, and I will return to you, says the Lord.', referenceEs: 'Malaquías 3:7', referenceEn: 'Malachi 3:7' },
  // — Mateo / Matthew —
  { textEs: 'Dichosos los misericordiosos, porque serán tratados con misericordia.', textEn: 'Blessed are the merciful, for they will be shown mercy.', referenceEs: 'Mateo 5:7', referenceEn: 'Matthew 5:7' },
  { textEs: 'Dichosos los de corazón limpio, porque ellos verán a Dios.', textEn: 'Blessed are the pure in heart, for they will see God.', referenceEs: 'Mateo 5:8', referenceEn: 'Matthew 5:8' },
  { textEs: 'Ustedes son la luz del mundo. Una ciudad en lo alto de una colina no puede esconderse.', textEn: 'You are the light of the world. A town built on a hill cannot be hidden.', referenceEs: 'Mateo 5:14', referenceEn: 'Matthew 5:14' },
  { textEs: 'Hagan brillar su luz delante de todos, para que ellos puedan ver las buenas obras de ustedes.', textEn: 'Let your light shine before others, that they may see your good deeds.', referenceEs: 'Mateo 5:16', referenceEn: 'Matthew 5:16' },
  { textEs: 'Busquen primeramente el reino de Dios y su justicia, y todas estas cosas les serán añadidas.', textEn: 'But seek first his kingdom and his righteousness, and all these things will be given to you as well.', referenceEs: 'Mateo 6:33', referenceEn: 'Matthew 6:33' },
  { textEs: 'No se preocupen por el mañana, que el mañana traerá sus propios afanes.', textEn: 'Therefore do not worry about tomorrow, for tomorrow will worry about itself.', referenceEs: 'Mateo 6:34', referenceEn: 'Matthew 6:34' },
  { textEs: 'Pidan, y se les dará; busquen, y encontrarán; llamen, y se les abrirá.', textEn: 'Ask and it will be given to you; seek and you will find; knock and the door will be opened to you.', referenceEs: 'Mateo 7:7', referenceEn: 'Matthew 7:7' },
  { textEs: 'Traten a los demás como quieran que ellos los traten a ustedes.', textEn: 'Do to others what you would have them do to you.', referenceEs: 'Mateo 7:12', referenceEn: 'Matthew 7:12' },
  { textEs: 'Vengan a mí todos ustedes que están cansados y agobiados, y yo les daré descanso.', textEn: 'Come to me, all you who are weary and burdened, and I will give you rest.', referenceEs: 'Mateo 11:28', referenceEn: 'Matthew 11:28' },
  { textEs: 'Para los hombres es imposible, mas para Dios todo es posible.', textEn: 'With man this is impossible, but with God all things are possible.', referenceEs: 'Mateo 19:26', referenceEn: 'Matthew 19:26' },
  { textEs: 'Ama al Señor tu Dios con todo tu corazón, con toda tu alma y con toda tu mente.', textEn: 'Love the Lord your God with all your heart and with all your soul and with all your mind.', referenceEs: 'Mateo 22:37', referenceEn: 'Matthew 22:37' },
  { textEs: 'Ama a tu prójimo como a ti mismo.', textEn: 'Love your neighbor as yourself.', referenceEs: 'Mateo 22:39', referenceEn: 'Matthew 22:39' },
  { textEs: 'El cielo y la tierra pasarán, pero mis palabras jamás pasarán.', textEn: 'Heaven and earth will pass away, but my words will never pass away.', referenceEs: 'Mateo 24:35', referenceEn: 'Matthew 24:35' },
  { textEs: '¡Bien hecho, siervo bueno y fiel!', textEn: 'Well done, good and faithful servant!', referenceEs: 'Mateo 25:21', referenceEn: 'Matthew 25:21' },
  { textEs: 'Cuanto hicieron por uno de mis hermanos más pequeños, por mí lo hicieron.', textEn: 'Whatever you did for one of the least of these brothers and sisters of mine, you did for me.', referenceEs: 'Mateo 25:40', referenceEn: 'Matthew 25:40' },
  { textEs: 'Vayan y hagan discípulos de todas las naciones.', textEn: 'Go and make disciples of all nations.', referenceEs: 'Mateo 28:19', referenceEn: 'Matthew 28:19' },
  { textEs: 'Y yo estaré con ustedes siempre, hasta el fin del mundo.', textEn: 'And surely I am with you always, to the very end of the age.', referenceEs: 'Mateo 28:20', referenceEn: 'Matthew 28:20' },
  { textEs: 'No solo de pan vive el hombre, sino de toda palabra que sale de la boca de Dios.', textEn: 'Man shall not live on bread alone, but on every word that comes from the mouth of God.', referenceEs: 'Mateo 4:4', referenceEn: 'Matthew 4:4' },
  { textEs: 'Dichosos los que tienen hambre y sed de justicia, porque serán saciados.', textEn: 'Blessed are those who hunger and thirst for righteousness, for they will be filled.', referenceEs: 'Mateo 5:6', referenceEn: 'Matthew 5:6' },
  { textEs: 'Dichosos los que trabajan por la paz, porque serán llamados hijos de Dios.', textEn: 'Blessed are the peacemakers, for they will be called children of God.', referenceEs: 'Mateo 5:9', referenceEn: 'Matthew 5:9' },
  // — Marcos / Mark —
  { textEs: '¡Sí creo! Ayúdame en mi poca fe.', textEn: 'I do believe; help me overcome my unbelief!', referenceEs: 'Marcos 9:24', referenceEn: 'Mark 9:24' },
  { textEs: 'El que quiera ser el primero deberá ser el último de todos y el servidor de todos.', textEn: 'Anyone who wants to be first must be the very last, and the servant of all.', referenceEs: 'Marcos 9:35', referenceEn: 'Mark 9:35' },
  { textEs: 'Para Dios todo es posible.', textEn: 'All things are possible with God.', referenceEs: 'Marcos 10:27', referenceEn: 'Mark 10:27' },
  { textEs: 'Tengan fe en Dios.', textEn: 'Have faith in God.', referenceEs: 'Marcos 11:22', referenceEn: 'Mark 11:22' },
  { textEs: 'Todo lo que pidan en oración, crean que ya lo han recibido, y lo obtendrán.', textEn: 'Whatever you ask for in prayer, believe that you have received it, and it will be yours.', referenceEs: 'Marcos 11:24', referenceEn: 'Mark 11:24' },
  { textEs: 'Amarás al Señor tu Dios con todo tu corazón; este es el mandamiento más importante.', textEn: 'Love the Lord your God with all your heart; this is the most important commandment.', referenceEs: 'Marcos 12:30', referenceEn: 'Mark 12:30' },
  { textEs: 'Vayan por todo el mundo y anuncien las buenas noticias.', textEn: 'Go into all the world and preach the gospel.', referenceEs: 'Marcos 16:15', referenceEn: 'Mark 16:15' },
  { textEs: 'Vengan conmigo a un lugar tranquilo para que descansen un poco.', textEn: 'Come with me by yourselves to a quiet place and get some rest.', referenceEs: 'Marcos 6:31', referenceEn: 'Mark 6:31' },
  // — Lucas / Luke —
  { textEs: 'Porque para Dios no hay nada imposible.', textEn: 'For no word from God will ever fail.', referenceEs: 'Lucas 1:37', referenceEn: 'Luke 1:37' },
  { textEs: 'Gloria a Dios en las alturas, y en la tierra paz a los que gozan de su buena voluntad.', textEn: 'Glory to God in the highest heaven, and on earth peace to those on whom his favor rests.', referenceEs: 'Lucas 2:14', referenceEn: 'Luke 2:14' },
  { textEs: 'Den, y se les dará: una medida buena, apretada, sacudida y desbordante.', textEn: 'Give, and it will be given to you. A good measure, pressed down, shaken together and running over.', referenceEs: 'Lucas 6:38', referenceEn: 'Luke 6:38' },
  { textEs: 'Amen a sus enemigos, háganles bien y présten sin esperar nada a cambio.', textEn: 'Love your enemies, do good to them, and lend without expecting to get anything back.', referenceEs: 'Lucas 6:35', referenceEn: 'Luke 6:35' },
  { textEs: 'No tengan miedo, rebaño pequeño, porque es la buena voluntad del Padre darles el reino.', textEn: 'Do not be afraid, little flock, for your Father has been pleased to give you the kingdom.', referenceEs: 'Lucas 12:32', referenceEn: 'Luke 12:32' },
  { textEs: 'Habrá más alegría en el cielo por un pecador que se arrepiente.', textEn: 'There will be more rejoicing in heaven over one sinner who repents.', referenceEs: 'Lucas 15:7', referenceEn: 'Luke 15:7' },
  { textEs: 'El que es fiel en lo poco, también es fiel en lo mucho.', textEn: 'Whoever is faithful in a very little is also faithful in much.', referenceEs: 'Lucas 16:10', referenceEn: 'Luke 16:10' },
  { textEs: 'El reino de Dios está entre ustedes.', textEn: 'The kingdom of God is in your midst.', referenceEs: 'Lucas 17:21', referenceEn: 'Luke 17:21' },
  { textEs: 'Lo que es imposible para los hombres es posible para Dios.', textEn: 'What is impossible with man is possible with God.', referenceEs: 'Lucas 18:27', referenceEn: 'Luke 18:27' },
  { textEs: 'El Hijo del Hombre vino a buscar y a salvar lo que se había perdido.', textEn: 'For the Son of Man came to seek and to save the lost.', referenceEs: 'Lucas 19:10', referenceEn: 'Luke 19:10' },
  { textEs: 'Padre, en tus manos encomiendo mi espíritu.', textEn: 'Father, into your hands I commit my spirit.', referenceEs: 'Lucas 23:46', referenceEn: 'Luke 23:46' },
  { textEs: 'Jesús crecía en sabiduría y en estatura, y en gracia para con Dios y los hombres.', textEn: 'And Jesus grew in wisdom and stature, and in favor with God and man.', referenceEs: 'Lucas 2:52', referenceEn: 'Luke 2:52' },
  { textEs: 'Pero busquen el reino de Dios, y estas cosas les serán añadidas.', textEn: 'But seek his kingdom, and these things will be given to you as well.', referenceEs: 'Lucas 12:31', referenceEn: 'Luke 12:31' },
  { textEs: 'María atesoraba todas estas cosas, y las meditaba en su corazón.', textEn: 'But Mary treasured up all these things and pondered them in her heart.', referenceEs: 'Lucas 2:19', referenceEn: 'Luke 2:19' },
  // — Juan / John —
  { textEs: 'En el principio ya existía la Palabra, y la Palabra estaba con Dios, y la Palabra era Dios.', textEn: 'In the beginning was the Word, and the Word was with God, and the Word was God.', referenceEs: 'Juan 1:1', referenceEn: 'John 1:1' },
  { textEs: 'La luz brilla en las tinieblas, y las tinieblas no han podido extinguirla.', textEn: 'The light shines in the darkness, and the darkness has not overcome it.', referenceEs: 'Juan 1:5', referenceEn: 'John 1:5' },
  { textEs: 'Tanto amó Dios al mundo que dio a su Hijo único, para que todo el que cree en él tenga vida eterna.', textEn: 'For God so loved the world that he gave his one and only Son, that whoever believes in him shall have eternal life.', referenceEs: 'Juan 3:16', referenceEn: 'John 3:16' },
  { textEs: 'El agua que yo le daré se convertirá en él en un manantial del que brotará vida eterna.', textEn: 'The water I give them will become in them a spring of water welling up to eternal life.', referenceEs: 'Juan 4:14', referenceEn: 'John 4:14' },
  { textEs: 'Yo soy el pan de vida; el que viene a mí nunca pasará hambre.', textEn: 'I am the bread of life. Whoever comes to me will never go hungry.', referenceEs: 'Juan 6:35', referenceEn: 'John 6:35' },
  { textEs: 'Yo soy la luz del mundo; el que me sigue no andará en tinieblas.', textEn: 'I am the light of the world. Whoever follows me will never walk in darkness.', referenceEs: 'Juan 8:12', referenceEn: 'John 8:12' },
  { textEs: 'Y conocerán la verdad, y la verdad los hará libres.', textEn: 'Then you will know the truth, and the truth will set you free.', referenceEs: 'Juan 8:32', referenceEn: 'John 8:32' },
  { textEs: 'Yo soy el buen pastor; el buen pastor da su vida por las ovejas.', textEn: 'I am the good shepherd. The good shepherd lays down his life for the sheep.', referenceEs: 'Juan 10:11', referenceEn: 'John 10:11' },
  { textEs: 'Yo soy la resurrección y la vida. El que cree en mí vivirá, aunque muera.', textEn: 'I am the resurrection and the life. The one who believes in me will live, even though they die.', referenceEs: 'Juan 11:25', referenceEn: 'John 11:25' },
  { textEs: 'Les doy un mandamiento nuevo: que se amen los unos a los otros, así como yo los he amado.', textEn: 'A new command I give you: Love one another. As I have loved you, so you must love one another.', referenceEs: 'Juan 13:34', referenceEn: 'John 13:34' },
  { textEs: 'No se angustien. Confíen en Dios, y confíen también en mí.', textEn: 'Do not let your hearts be troubled. You believe in God; believe also in me.', referenceEs: 'Juan 14:1', referenceEn: 'John 14:1' },
  { textEs: 'Yo soy el camino, la verdad y la vida.', textEn: 'I am the way and the truth and the life.', referenceEs: 'Juan 14:6', referenceEn: 'John 14:6' },
  { textEs: 'La paz les dejo; mi paz les doy. No se angustien ni se acobarden.', textEn: 'Peace I leave with you; my peace I give you. Do not let your hearts be troubled and do not be afraid.', referenceEs: 'Juan 14:27', referenceEn: 'John 14:27' },
  { textEs: 'Yo soy la vid y ustedes son las ramas. El que permanece en mí da mucho fruto.', textEn: 'I am the vine; you are the branches. If you remain in me, you will bear much fruit.', referenceEs: 'Juan 15:5', referenceEn: 'John 15:5' },
  { textEs: 'Nadie tiene amor más grande que el dar la vida por sus amigos.', textEn: 'Greater love has no one than this: to lay down one’s life for one’s friends.', referenceEs: 'Juan 15:13', referenceEn: 'John 15:13' },
  { textEs: 'En este mundo tendrán aflicción; pero ¡anímense! Yo he vencido al mundo.', textEn: 'In this world you will have trouble. But take heart! I have overcome the world.', referenceEs: 'Juan 16:33', referenceEn: 'John 16:33' },
  { textEs: 'Dichosos los que no han visto y sin embargo creen.', textEn: 'Blessed are those who have not seen and yet have believed.', referenceEs: 'Juan 20:29', referenceEn: 'John 20:29' },
  { textEs: 'Si permanecen en mi palabra, serán verdaderamente mis discípulos.', textEn: 'If you hold to my teaching, you are really my disciples.', referenceEs: 'Juan 8:31', referenceEn: 'John 8:31' },
  { textEs: 'Yo he venido para que tengan vida, y la tengan en abundancia.', textEn: 'I have come that they may have life, and have it to the full.', referenceEs: 'Juan 10:10', referenceEn: 'John 10:10' },
  { textEs: 'Mis ovejas oyen mi voz; yo las conozco y ellas me siguen.', textEn: 'My sheep listen to my voice; I know them, and they follow me.', referenceEs: 'Juan 10:27', referenceEn: 'John 10:27' },
  // — Hechos / Acts —
  { textEs: 'Recibirán poder cuando el Espíritu Santo venga sobre ustedes, y serán mis testigos.', textEn: 'You will receive power when the Holy Spirit comes on you; and you will be my witnesses.', referenceEs: 'Hechos 1:8', referenceEn: 'Acts 1:8' },
  { textEs: 'En ningún otro hay salvación.', textEn: 'Salvation is found in no one else.', referenceEs: 'Hechos 4:12', referenceEn: 'Acts 4:12' },
  { textEs: 'Hay más dicha en dar que en recibir.', textEn: 'It is more blessed to give than to receive.', referenceEs: 'Hechos 20:35', referenceEn: 'Acts 20:35' },
  { textEs: 'Cree en el Señor Jesús, y serás salvo, tú y tu familia.', textEn: 'Believe in the Lord Jesus, and you will be saved—you and your household.', referenceEs: 'Hechos 16:31', referenceEn: 'Acts 16:31' },
  { textEs: 'En él vivimos, nos movemos y existimos.', textEn: 'For in him we live and move and have our being.', referenceEs: 'Hechos 17:28', referenceEn: 'Acts 17:28' },
  { textEs: 'Todo el que invoque el nombre del Señor será salvo.', textEn: 'And everyone who calls on the name of the Lord will be saved.', referenceEs: 'Hechos 2:21', referenceEn: 'Acts 2:21' },
  // — Romanos / Romans —
  { textEs: 'No me avergüenzo del evangelio, pues es poder de Dios para la salvación.', textEn: 'For I am not ashamed of the gospel, because it is the power of God that brings salvation.', referenceEs: 'Romanos 1:16', referenceEn: 'Romans 1:16' },
  { textEs: 'Todos pecaron y están privados de la gloria de Dios.', textEn: 'For all have sinned and fall short of the glory of God.', referenceEs: 'Romanos 3:23', referenceEn: 'Romans 3:23' },
  { textEs: 'Tenemos paz con Dios por medio de nuestro Señor Jesucristo.', textEn: 'We have peace with God through our Lord Jesus Christ.', referenceEs: 'Romanos 5:1', referenceEn: 'Romans 5:1' },
  { textEs: 'Dios demuestra su amor por nosotros en que, cuando todavía éramos pecadores, Cristo murió por nosotros.', textEn: 'But God demonstrates his own love for us in this: While we were still sinners, Christ died for us.', referenceEs: 'Romanos 5:8', referenceEn: 'Romans 5:8' },
  { textEs: 'La dádiva de Dios es vida eterna en Cristo Jesús, nuestro Señor.', textEn: 'The gift of God is eternal life in Christ Jesus our Lord.', referenceEs: 'Romanos 6:23', referenceEn: 'Romans 6:23' },
  { textEs: 'Ya no hay ninguna condenación para los que están unidos a Cristo Jesús.', textEn: 'Therefore, there is now no condemnation for those who are in Christ Jesus.', referenceEs: 'Romanos 8:1', referenceEn: 'Romans 8:1' },
  { textEs: 'Sabemos que Dios dispone todas las cosas para el bien de quienes lo aman.', textEn: 'And we know that in all things God works for the good of those who love him.', referenceEs: 'Romanos 8:28', referenceEn: 'Romans 8:28' },
  { textEs: 'Si Dios está de nuestra parte, ¿quién puede estar en contra nuestra?', textEn: 'If God is for us, who can be against us?', referenceEs: 'Romanos 8:31', referenceEn: 'Romans 8:31' },
  { textEs: 'Nada podrá separarnos del amor que Dios nos ha manifestado en Cristo Jesús.', textEn: 'Nothing will be able to separate us from the love of God that is in Christ Jesus our Lord.', referenceEs: 'Romanos 8:39', referenceEn: 'Romans 8:39' },
  { textEs: 'No se amolden al mundo actual, sino sean transformados mediante la renovación de su mente.', textEn: 'Do not conform to the pattern of this world, but be transformed by the renewing of your mind.', referenceEs: 'Romanos 12:2', referenceEn: 'Romans 12:2' },
  { textEs: 'Alégrense con los que están alegres; lloren con los que lloran.', textEn: 'Rejoice with those who rejoice; mourn with those who mourn.', referenceEs: 'Romanos 12:15', referenceEn: 'Romans 12:15' },
  { textEs: 'No te dejes vencer por el mal; al contrario, vence el mal con el bien.', textEn: 'Do not be overcome by evil, but overcome evil with good.', referenceEs: 'Romanos 12:21', referenceEn: 'Romans 12:21' },
  { textEs: 'Que el Dios de la esperanza los llene de toda alegría y paz a ustedes que creen en él.', textEn: 'May the God of hope fill you with all joy and peace as you trust in him.', referenceEs: 'Romanos 15:13', referenceEn: 'Romans 15:13' },
  { textEs: 'El amor sea sincero. Aborrezcan el mal; aférrense al bien.', textEn: 'Love must be sincere. Hate what is evil; cling to what is good.', referenceEs: 'Romanos 12:9', referenceEn: 'Romans 12:9' },
  { textEs: 'Si confiesas con tu boca que Jesús es el Señor, y crees en tu corazón, serás salvo.', textEn: 'If you declare with your mouth, “Jesus is Lord,” and believe in your heart, you will be saved.', referenceEs: 'Romanos 10:9', referenceEn: 'Romans 10:9' },
  { textEs: 'La fe viene como resultado de oír el mensaje, y el mensaje que se oye es la palabra de Cristo.', textEn: 'Faith comes from hearing the message, and the message is heard through the word about Christ.', referenceEs: 'Romanos 10:17', referenceEn: 'Romans 10:17' },
  { textEs: 'En cuanto dependa de ustedes, vivan en paz con todos.', textEn: 'If it is possible, as far as it depends on you, live at peace with everyone.', referenceEs: 'Romanos 12:18', referenceEn: 'Romans 12:18' },
  { textEs: 'Sean diligentes, no perezosos; sirvan al Señor con fervor de espíritu.', textEn: 'Never be lacking in zeal, but keep your spiritual fervor, serving the Lord.', referenceEs: 'Romanos 12:11', referenceEn: 'Romans 12:11' },
  // — 1 Corintios / 1 Corinthians —
  { textEs: 'Ya sea que coman o beban o hagan cualquier otra cosa, háganlo todo para la gloria de Dios.', textEn: 'So whether you eat or drink or whatever you do, do it all for the glory of God.', referenceEs: '1 Corintios 10:31', referenceEn: '1 Corinthians 10:31' },
  { textEs: 'Dios es fiel, y no permitirá que sean tentados más allá de lo que puedan soportar.', textEn: 'God is faithful; he will not let you be tempted beyond what you can bear.', referenceEs: '1 Corintios 10:13', referenceEn: '1 Corinthians 10:13' },
  { textEs: 'El amor es paciente, es bondadoso. El amor no es envidioso ni jactancioso ni orgulloso.', textEn: 'Love is patient, love is kind. It does not envy, it does not boast, it is not proud.', referenceEs: '1 Corintios 13:4', referenceEn: '1 Corinthians 13:4' },
  { textEs: 'El amor todo lo disculpa, todo lo cree, todo lo espera, todo lo soporta.', textEn: 'Love always protects, always trusts, always hopes, always perseveres.', referenceEs: '1 Corintios 13:7', referenceEn: '1 Corinthians 13:7' },
  { textEs: 'Ahora permanecen estas tres: la fe, la esperanza y el amor. Pero el más excelente es el amor.', textEn: 'And now these three remain: faith, hope and love. But the greatest of these is love.', referenceEs: '1 Corintios 13:13', referenceEn: '1 Corinthians 13:13' },
  { textEs: 'Manténganse alerta; permanezcan firmes en la fe; sean valientes y fuertes.', textEn: 'Be on your guard; stand firm in the faith; be courageous; be strong.', referenceEs: '1 Corintios 16:13', referenceEn: '1 Corinthians 16:13' },
  { textEs: 'Hagan todo con amor.', textEn: 'Do everything in love.', referenceEs: '1 Corintios 16:14', referenceEn: '1 Corinthians 16:14' },
  { textEs: '¿No saben que su cuerpo es templo del Espíritu Santo?', textEn: 'Do you not know that your bodies are temples of the Holy Spirit?', referenceEs: '1 Corintios 6:19', referenceEn: '1 Corinthians 6:19' },
  { textEs: 'Ningún ojo vio, ni oído escuchó lo que Dios ha preparado para quienes lo aman.', textEn: 'What no eye has seen, what no ear has heard, God has prepared for those who love him.', referenceEs: '1 Corintios 2:9', referenceEn: '1 Corinthians 2:9' },
  { textEs: 'Por lo tanto, mis queridos hermanos, manténganse firmes e inconmovibles.', textEn: 'Therefore, my dear brothers and sisters, stand firm. Let nothing move you.', referenceEs: '1 Corintios 15:58', referenceEn: '1 Corinthians 15:58' },
  { textEs: 'Todo sea hecho de manera apropiada y con orden.', textEn: 'Everything should be done in a fitting and orderly way.', referenceEs: '1 Corintios 14:40', referenceEn: '1 Corinthians 14:40' },
  { textEs: 'Cuando yo era niño, hablaba como niño; ya soy un hombre, y he dejado atrás las cosas de niño.', textEn: 'When I was a child, I talked like a child; when I became a man, I put the ways of childhood behind me.', referenceEs: '1 Corintios 13:11', referenceEn: '1 Corinthians 13:11' },
  // — 2 Corintios / 2 Corinthians —
  { textEs: 'El Dios de toda consolación nos consuela en todas nuestras tribulaciones.', textEn: 'The God of all comfort, who comforts us in all our troubles.', referenceEs: '2 Corintios 1:3-4', referenceEn: '2 Corinthians 1:3-4' },
  { textEs: 'Por eso, si alguno está en Cristo, es una nueva creación.', textEn: 'Therefore, if anyone is in Christ, the new creation has come.', referenceEs: '2 Corintios 5:17', referenceEn: '2 Corinthians 5:17' },
  { textEs: 'Vivimos por fe, no por vista.', textEn: 'For we live by faith, not by sight.', referenceEs: '2 Corintios 5:7', referenceEn: '2 Corinthians 5:7' },
  { textEs: 'Te basta con mi gracia, pues mi poder se perfecciona en la debilidad.', textEn: 'My grace is sufficient for you, for my power is made perfect in weakness.', referenceEs: '2 Corintios 12:9', referenceEn: '2 Corinthians 12:9' },
  { textEs: 'Dios ama al que da con alegría.', textEn: 'God loves a cheerful giver.', referenceEs: '2 Corintios 9:7', referenceEn: '2 Corinthians 9:7' },
  { textEs: 'No nos fijamos en lo visible, sino en lo invisible, ya que lo que se ve es pasajero.', textEn: 'So we fix our eyes not on what is seen, but on what is unseen, since what is seen is temporary.', referenceEs: '2 Corintios 4:18', referenceEn: '2 Corinthians 4:18' },
  { textEs: 'Por eso no nos desanimamos. Aunque por fuera nos vamos desgastando, por dentro nos renovamos día tras día.', textEn: 'Therefore we do not lose heart. Though outwardly we are wasting away, yet inwardly we are being renewed day by day.', referenceEs: '2 Corintios 4:16', referenceEn: '2 Corinthians 4:16' },
  { textEs: 'Donde está el Espíritu del Señor, allí hay libertad.', textEn: 'Where the Spirit of the Lord is, there is freedom.', referenceEs: '2 Corintios 3:17', referenceEn: '2 Corinthians 3:17' },
  { textEs: 'Tenemos este tesoro en vasijas de barro, para que se vea que tan sublime poder viene de Dios.', textEn: 'But we have this treasure in jars of clay to show that this all-surpassing power is from God.', referenceEs: '2 Corintios 4:7', referenceEn: '2 Corinthians 4:7' },
  { textEs: 'La gracia del Señor Jesucristo, el amor de Dios y la comunión del Espíritu Santo sean con todos.', textEn: 'May the grace of the Lord Jesus Christ, and the love of God, and the fellowship of the Holy Spirit be with you all.', referenceEs: '2 Corintios 13:14', referenceEn: '2 Corinthians 13:14' },
  // — Gálatas / Galatians —
  { textEs: 'Ya no vivo yo, sino que Cristo vive en mí.', textEn: 'I no longer live, but Christ lives in me.', referenceEs: 'Gálatas 2:20', referenceEn: 'Galatians 2:20' },
  { textEs: 'El fruto del Espíritu es amor, alegría, paz, paciencia, amabilidad, bondad, fidelidad.', textEn: 'But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness.', referenceEs: 'Gálatas 5:22', referenceEn: 'Galatians 5:22' },
  { textEs: 'No nos cansemos de hacer el bien, porque a su debido tiempo cosecharemos si no nos damos por vencidos.', textEn: 'Let us not become weary in doing good, for at the proper time we will reap a harvest if we do not give up.', referenceEs: 'Gálatas 6:9', referenceEn: 'Galatians 6:9' },
  { textEs: 'Ayúdense unos a otros a llevar sus cargas, y así cumplirán la ley de Cristo.', textEn: 'Carry each other’s burdens, and in this way you will fulfill the law of Christ.', referenceEs: 'Gálatas 6:2', referenceEn: 'Galatians 6:2' },
  { textEs: 'Ya no hay judío ni griego; todos ustedes son uno en Cristo Jesús.', textEn: 'There is neither Jew nor Gentile; for you are all one in Christ Jesus.', referenceEs: 'Gálatas 3:28', referenceEn: 'Galatians 3:28' },
  { textEs: 'Cristo nos libertó para que vivamos en libertad.', textEn: 'It is for freedom that Christ has set us free.', referenceEs: 'Gálatas 5:1', referenceEn: 'Galatians 5:1' },
  { textEs: 'Cada uno cargue con su propia responsabilidad.', textEn: 'For each one should carry their own load.', referenceEs: 'Gálatas 6:5', referenceEn: 'Galatians 6:5' },
  // — Efesios / Ephesians —
  { textEs: 'Somos hechura de Dios, creados en Cristo Jesús para buenas obras.', textEn: 'For we are God’s handiwork, created in Christ Jesus to do good works.', referenceEs: 'Efesios 2:10', referenceEn: 'Ephesians 2:10' },
  { textEs: 'Por gracia ustedes han sido salvados mediante la fe; esto no procede de ustedes, sino que es el regalo de Dios.', textEn: 'For it is by grace you have been saved, through faith—and this is not from yourselves, it is the gift of God.', referenceEs: 'Efesios 2:8', referenceEn: 'Ephesians 2:8' },
  { textEs: 'Sean bondadosos y compasivos unos con otros, y perdónense mutuamente.', textEn: 'Be kind and compassionate to one another, forgiving each other.', referenceEs: 'Efesios 4:32', referenceEn: 'Ephesians 4:32' },
  { textEs: 'Sean imitadores de Dios, como hijos muy amados.', textEn: 'Follow God’s example, therefore, as dearly loved children.', referenceEs: 'Efesios 5:1', referenceEn: 'Ephesians 5:1' },
  { textEs: 'Fortalézcanse con el gran poder del Señor.', textEn: 'Be strong in the Lord and in his mighty power.', referenceEs: 'Efesios 6:10', referenceEn: 'Ephesians 6:10' },
  { textEs: 'Pónganse toda la armadura de Dios para poder hacer frente a las artimañas del diablo.', textEn: 'Put on the full armor of God, so that you can take your stand against the devil’s schemes.', referenceEs: 'Efesios 6:11', referenceEn: 'Ephesians 6:11' },
  { textEs: 'A aquel que puede hacer muchísimo más que todo lo que podamos imaginar, sea la gloria.', textEn: 'Now to him who is able to do immeasurably more than all we ask or imagine, to him be glory.', referenceEs: 'Efesios 3:20-21', referenceEn: 'Ephesians 3:20-21' },
  { textEs: 'Sean humildes y amables; sean pacientes, y tolérense unos a otros en amor.', textEn: 'Be completely humble and gentle; be patient, bearing with one another in love.', referenceEs: 'Efesios 4:2', referenceEn: 'Ephesians 4:2' },
  { textEs: 'No salga de la boca de ustedes ninguna palabra mala, sino solo la que edifique.', textEn: 'Do not let any unwholesome talk come out of your mouths, but only what is helpful for building others up.', referenceEs: 'Efesios 4:29', referenceEn: 'Ephesians 4:29' },
  { textEs: 'Vivan como hijos de luz.', textEn: 'Live as children of light.', referenceEs: 'Efesios 5:8', referenceEn: 'Ephesians 5:8' },
  { textEs: 'Aprovechen al máximo cada momento oportuno.', textEn: 'Making the most of every opportunity.', referenceEs: 'Efesios 5:16', referenceEn: 'Ephesians 5:16' },
  { textEs: 'Sean renovados en la actitud de su mente.', textEn: 'Be made new in the attitude of your minds.', referenceEs: 'Efesios 4:23', referenceEn: 'Ephesians 4:23' },
  // — Filipenses / Philippians —
  { textEs: 'El que comenzó en ustedes la buena obra la irá perfeccionando hasta el día de Cristo Jesús.', textEn: 'He who began a good work in you will carry it on to completion until the day of Christ Jesus.', referenceEs: 'Filipenses 1:6', referenceEn: 'Philippians 1:6' },
  { textEs: 'Con humildad consideren a los demás como superiores a ustedes mismos.', textEn: 'In humility value others above yourselves.', referenceEs: 'Filipenses 2:3', referenceEn: 'Philippians 2:3' },
  { textEs: 'Háganlo todo sin quejas ni contiendas.', textEn: 'Do everything without grumbling or arguing.', referenceEs: 'Filipenses 2:14', referenceEn: 'Philippians 2:14' },
  { textEs: 'Sigo avanzando hacia la meta para ganar el premio que Dios ofrece.', textEn: 'I press on toward the goal to win the prize for which God has called me heavenward.', referenceEs: 'Filipenses 3:14', referenceEn: 'Philippians 3:14' },
  { textEs: 'Alégrense siempre en el Señor. Insisto: ¡alégrense!', textEn: 'Rejoice in the Lord always. I will say it again: Rejoice!', referenceEs: 'Filipenses 4:4', referenceEn: 'Philippians 4:4' },
  { textEs: 'No se inquieten por nada; más bien, en toda ocasión, presenten sus peticiones a Dios.', textEn: 'Do not be anxious about anything, but in every situation, present your requests to God.', referenceEs: 'Filipenses 4:6', referenceEn: 'Philippians 4:6' },
  { textEs: 'La paz de Dios cuidará sus corazones y sus pensamientos en Cristo Jesús.', textEn: 'And the peace of God will guard your hearts and your minds in Christ Jesus.', referenceEs: 'Filipenses 4:7', referenceEn: 'Philippians 4:7' },
  { textEs: 'Consideren bien todo lo verdadero, lo respetable, lo justo, lo puro, lo amable.', textEn: 'Whatever is true, whatever is noble, whatever is right, whatever is pure, whatever is lovely—think about such things.', referenceEs: 'Filipenses 4:8', referenceEn: 'Philippians 4:8' },
  { textEs: 'Todo lo puedo en Cristo que me fortalece.', textEn: 'I can do all things through Christ who strengthens me.', referenceEs: 'Filipenses 4:13', referenceEn: 'Philippians 4:13' },
  // — Colosenses / Colossians —
  { textEs: 'Concentren su atención en las cosas de arriba, no en las de la tierra.', textEn: 'Set your minds on things above, not on earthly things.', referenceEs: 'Colosenses 3:2', referenceEn: 'Colossians 3:2' },
  { textEs: 'Y por sobre todas estas cosas, vístanse de amor, que es el vínculo perfecto.', textEn: 'And over all these virtues put on love, which binds them all together in perfect unity.', referenceEs: 'Colosenses 3:14', referenceEn: 'Colossians 3:14' },
  { textEs: 'Que la paz de Cristo gobierne en sus corazones.', textEn: 'Let the peace of Christ rule in your hearts.', referenceEs: 'Colosenses 3:15', referenceEn: 'Colossians 3:15' },
  { textEs: 'Hagan lo que hagan, trabajen de buena gana, como para el Señor y no como para nadie en este mundo.', textEn: 'Whatever you do, work at it with all your heart, as working for the Lord, not for human masters.', referenceEs: 'Colosenses 3:23', referenceEn: 'Colossians 3:23' },
  { textEs: 'Que su conversación sea siempre amena y de buen gusto.', textEn: 'Let your conversation be always full of grace, seasoned with salt.', referenceEs: 'Colosenses 4:6', referenceEn: 'Colossians 4:6' },
  { textEs: 'Dedíquense a la oración: perseveren en ella con agradecimiento.', textEn: 'Devote yourselves to prayer, being watchful and thankful.', referenceEs: 'Colosenses 4:2', referenceEn: 'Colossians 4:2' },
  { textEs: 'Sean pacientes, soportándose unos a otros y perdonándose si alguno tiene queja contra otro.', textEn: 'Bear with each other and forgive one another if any of you has a grievance against someone.', referenceEs: 'Colosenses 3:13', referenceEn: 'Colossians 3:13' },
  { textEs: 'Todo lo que hagan, de palabra o de obra, háganlo en el nombre del Señor Jesús.', textEn: 'And whatever you do, whether in word or deed, do it all in the name of the Lord Jesus.', referenceEs: 'Colosenses 3:17', referenceEn: 'Colossians 3:17' },
  // — 1 Tesalonicenses / 1 Thessalonians —
  { textEs: 'Anímense y edifíquense unos a otros, tal como lo vienen haciendo.', textEn: 'Therefore encourage one another and build each other up, just as in fact you are doing.', referenceEs: '1 Tesalonicenses 5:11', referenceEn: '1 Thessalonians 5:11' },
  { textEs: 'Estén siempre alegres, oren sin cesar, den gracias a Dios en toda situación.', textEn: 'Rejoice always, pray continually, give thanks in all circumstances.', referenceEs: '1 Tesalonicenses 5:16-18', referenceEn: '1 Thessalonians 5:16-18' },
  { textEs: 'Examínenlo todo; retengan lo bueno.', textEn: 'Test them all; hold on to what is good.', referenceEs: '1 Tesalonicenses 5:21', referenceEn: '1 Thessalonians 5:21' },
  { textEs: 'Procuren vivir en paz con todos, y esfuércense por progresar.', textEn: 'Make it your ambition to lead a quiet life and to work with your hands.', referenceEs: '1 Tesalonicenses 4:11', referenceEn: '1 Thessalonians 4:11' },
  // — 2 Tesalonicenses / 2 Thessalonians —
  { textEs: 'El Señor es fiel, y él los fortalecerá y los protegerá del maligno.', textEn: 'But the Lord is faithful, and he will strengthen you and protect you from the evil one.', referenceEs: '2 Tesalonicenses 3:3', referenceEn: '2 Thessalonians 3:3' },
  { textEs: 'No se cansen de hacer el bien.', textEn: 'Never tire of doing what is good.', referenceEs: '2 Tesalonicenses 3:13', referenceEn: '2 Thessalonians 3:13' },
  // — 1 Timoteo / 1 Timothy —
  { textEs: 'Que nadie te menosprecie por ser joven. Al contrario, sé ejemplo de los creyentes.', textEn: 'Don’t let anyone look down on you because you are young, but set an example for the believers.', referenceEs: '1 Timoteo 4:12', referenceEn: '1 Timothy 4:12' },
  { textEs: 'La gran ganancia está en la piedad acompañada de contentamiento.', textEn: 'But godliness with contentment is great gain.', referenceEs: '1 Timoteo 6:6', referenceEn: '1 Timothy 6:6' },
  { textEs: 'Pelea la buena batalla de la fe.', textEn: 'Fight the good fight of the faith.', referenceEs: '1 Timoteo 6:12', referenceEn: '1 Timothy 6:12' },
  { textEs: 'Hay un solo Dios y un solo mediador entre Dios y los hombres: Jesucristo.', textEn: 'For there is one God and one mediator between God and mankind, the man Christ Jesus.', referenceEs: '1 Timoteo 2:5', referenceEn: '1 Timothy 2:5' },
  // — 2 Timoteo / 2 Timothy —
  { textEs: 'Dios no nos ha dado un espíritu de cobardía, sino de poder, de amor y de buen juicio.', textEn: 'For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline.', referenceEs: '2 Timoteo 1:7', referenceEn: '2 Timothy 1:7' },
  { textEs: 'Esfuérzate por presentarte a Dios aprobado, como obrero que no tiene de qué avergonzarse.', textEn: 'Do your best to present yourself to God as one approved, a worker who does not need to be ashamed.', referenceEs: '2 Timoteo 2:15', referenceEn: '2 Timothy 2:15' },
  { textEs: 'Toda la Escritura es inspirada por Dios y útil para enseñar.', textEn: 'All Scripture is God-breathed and is useful for teaching.', referenceEs: '2 Timoteo 3:16', referenceEn: '2 Timothy 3:16' },
  { textEs: 'He peleado la buena batalla, he terminado la carrera, me he mantenido en la fe.', textEn: 'I have fought the good fight, I have finished the race, I have kept the faith.', referenceEs: '2 Timoteo 4:7', referenceEn: '2 Timothy 4:7' },
  { textEs: 'Si somos infieles, él sigue siendo fiel, ya que no puede negarse a sí mismo.', textEn: 'If we are faithless, he remains faithful, for he cannot disown himself.', referenceEs: '2 Timoteo 2:13', referenceEn: '2 Timothy 2:13' },
  // — Tito / Titus —
  { textEs: 'En todo ofréceles tu ejemplo de buenas obras.', textEn: 'In everything set them an example by doing what is good.', referenceEs: 'Tito 2:7', referenceEn: 'Titus 2:7' },
  { textEs: 'Él nos salvó, no por nuestras propias obras, sino por su misericordia.', textEn: 'He saved us, not because of righteous things we had done, but because of his mercy.', referenceEs: 'Tito 3:5', referenceEn: 'Titus 3:5' },
  // — Hebreos / Hebrews —
  { textEs: 'La fe es la garantía de lo que se espera, la certeza de lo que no se ve.', textEn: 'Now faith is confidence in what we hope for and assurance about what we do not see.', referenceEs: 'Hebreos 11:1', referenceEn: 'Hebrews 11:1' },
  { textEs: 'Sin fe es imposible agradar a Dios.', textEn: 'And without faith it is impossible to please God.', referenceEs: 'Hebreos 11:6', referenceEn: 'Hebrews 11:6' },
  { textEs: 'Corramos con perseverancia la carrera que tenemos por delante.', textEn: 'Let us run with perseverance the race marked out for us.', referenceEs: 'Hebreos 12:1', referenceEn: 'Hebrews 12:1' },
  { textEs: 'Fijemos la mirada en Jesús, el iniciador y perfeccionador de nuestra fe.', textEn: 'Fixing our eyes on Jesus, the pioneer and perfecter of faith.', referenceEs: 'Hebreos 12:2', referenceEn: 'Hebrews 12:2' },
  { textEs: 'Jesucristo es el mismo ayer, hoy y por los siglos.', textEn: 'Jesus Christ is the same yesterday and today and forever.', referenceEs: 'Hebreos 13:8', referenceEn: 'Hebrews 13:8' },
  { textEs: 'Nunca te dejaré; jamás te abandonaré.', textEn: 'Never will I leave you; never will I forsake you.', referenceEs: 'Hebreos 13:5', referenceEn: 'Hebrews 13:5' },
  { textEs: 'Acerquémonos confiadamente al trono de la gracia para recibir misericordia y hallar ayuda.', textEn: 'Let us then approach God’s throne of grace with confidence, so that we may receive mercy and find help.', referenceEs: 'Hebreos 4:16', referenceEn: 'Hebrews 4:16' },
  { textEs: 'La palabra de Dios es viva y eficaz, y más cortante que cualquier espada de dos filos.', textEn: 'For the word of God is alive and active. Sharper than any double-edged sword.', referenceEs: 'Hebreos 4:12', referenceEn: 'Hebrews 4:12' },
  { textEs: 'Mantengamos firme la esperanza que profesamos, porque fiel es quien hizo la promesa.', textEn: 'Let us hold unswervingly to the hope we profess, for he who promised is faithful.', referenceEs: 'Hebreos 10:23', referenceEn: 'Hebrews 10:23' },
  { textEs: 'Preocupémonos los unos por los otros, a fin de estimularnos al amor y a las buenas obras.', textEn: 'And let us consider how we may spur one another on toward love and good deeds.', referenceEs: 'Hebreos 10:24', referenceEn: 'Hebrews 10:24' },
  { textEs: 'No se olviden de practicar la hospitalidad.', textEn: 'Do not forget to show hospitality to strangers.', referenceEs: 'Hebreos 13:2', referenceEn: 'Hebrews 13:2' },
  // — Santiago / James —
  { textEs: 'Si a alguno de ustedes le falta sabiduría, pídasela a Dios, y él se la dará.', textEn: 'If any of you lacks wisdom, you should ask God, who gives generously to all.', referenceEs: 'Santiago 1:5', referenceEn: 'James 1:5' },
  { textEs: 'Todos deben estar listos para escuchar, y ser lentos para hablar y para enojarse.', textEn: 'Everyone should be quick to listen, slow to speak and slow to become angry.', referenceEs: 'Santiago 1:19', referenceEn: 'James 1:19' },
  { textEs: 'No se contenten solo con escuchar la palabra; pónganla en práctica.', textEn: 'Do not merely listen to the word. Do what it says.', referenceEs: 'Santiago 1:22', referenceEn: 'James 1:22' },
  { textEs: 'La fe sin obras está muerta.', textEn: 'Faith by itself, if it is not accompanied by action, is dead.', referenceEs: 'Santiago 2:17', referenceEn: 'James 2:17' },
  { textEs: 'Acérquense a Dios, y él se acercará a ustedes.', textEn: 'Come near to God and he will come near to you.', referenceEs: 'Santiago 4:8', referenceEn: 'James 4:8' },
  { textEs: 'Humíllense delante del Señor, y él los exaltará.', textEn: 'Humble yourselves before the Lord, and he will lift you up.', referenceEs: 'Santiago 4:10', referenceEn: 'James 4:10' },
  { textEs: 'La oración del justo es poderosa y eficaz.', textEn: 'The prayer of a righteous person is powerful and effective.', referenceEs: 'Santiago 5:16', referenceEn: 'James 5:16' },
  { textEs: 'Toda buena dádiva y todo don perfecto descienden de lo alto.', textEn: 'Every good and perfect gift is from above.', referenceEs: 'Santiago 1:17', referenceEn: 'James 1:17' },
  { textEs: 'Consideren un gran gozo cuando tengan que enfrentar diversas pruebas.', textEn: 'Consider it pure joy whenever you face trials of many kinds.', referenceEs: 'Santiago 1:2', referenceEn: 'James 1:2' },
  { textEs: 'La constancia debe llevar a feliz término la obra, para que sean perfectos e íntegros.', textEn: 'Let perseverance finish its work so that you may be mature and complete.', referenceEs: 'Santiago 1:4', referenceEn: 'James 1:4' },
  // — 1 Pedro / 1 Peter —
  { textEs: 'Depositen en él toda ansiedad, porque él cuida de ustedes.', textEn: 'Cast all your anxiety on him because he cares for you.', referenceEs: '1 Pedro 5:7', referenceEn: '1 Peter 5:7' },
  { textEs: 'Humíllense bajo la poderosa mano de Dios, para que él los exalte a su debido tiempo.', textEn: 'Humble yourselves under God’s mighty hand, that he may lift you up in due time.', referenceEs: '1 Pedro 5:6', referenceEn: '1 Peter 5:6' },
  { textEs: 'Sobre todo, ámense los unos a los otros profundamente, porque el amor cubre multitud de pecados.', textEn: 'Above all, love each other deeply, because love covers over a multitude of sins.', referenceEs: '1 Pedro 4:8', referenceEn: '1 Peter 4:8' },
  { textEs: 'Cada uno ponga al servicio de los demás el don que haya recibido.', textEn: 'Each of you should use whatever gift you have received to serve others.', referenceEs: '1 Pedro 4:10', referenceEn: '1 Peter 4:10' },
  { textEs: 'Estén siempre preparados para responder a todo el que les pida razón de su esperanza.', textEn: 'Always be prepared to give an answer to everyone who asks you to give the reason for the hope that you have.', referenceEs: '1 Pedro 3:15', referenceEn: '1 Peter 3:15' },
  { textEs: 'Por sus heridas ustedes han sido sanados.', textEn: 'By his wounds you have been healed.', referenceEs: '1 Pedro 2:24', referenceEn: '1 Peter 2:24' },
  { textEs: 'Manténganse alerta y firmes en la fe.', textEn: 'Be alert and of sober mind. Resist the devil, standing firm in the faith.', referenceEs: '1 Pedro 5:8-9', referenceEn: '1 Peter 5:8-9' },
  { textEs: 'Ustedes son linaje escogido, real sacerdocio, nación santa.', textEn: 'But you are a chosen people, a royal priesthood, a holy nation.', referenceEs: '1 Pedro 2:9', referenceEn: '1 Peter 2:9' },
  { textEs: 'Sean todos de un mismo sentir; compartan penas y alegrías, y sean compasivos y humildes.', textEn: 'Finally, all of you, be like-minded, be sympathetic, love one another, be compassionate and humble.', referenceEs: '1 Pedro 3:8', referenceEn: '1 Peter 3:8' },
  // — 2 Pedro / 2 Peter —
  { textEs: 'El Señor no tarda en cumplir su promesa, sino que tiene paciencia con ustedes.', textEn: 'The Lord is not slow in keeping his promise. Instead he is patient with you.', referenceEs: '2 Pedro 3:9', referenceEn: '2 Peter 3:9' },
  { textEs: 'Crezcan en la gracia y en el conocimiento de nuestro Señor y Salvador Jesucristo.', textEn: 'But grow in the grace and knowledge of our Lord and Savior Jesus Christ.', referenceEs: '2 Pedro 3:18', referenceEn: '2 Peter 3:18' },
  { textEs: 'Su divino poder nos ha concedido todas las cosas que necesitamos para vivir como Dios manda.', textEn: 'His divine power has given us everything we need for a godly life.', referenceEs: '2 Pedro 1:3', referenceEn: '2 Peter 1:3' },
  // — 1 Juan / 1 John —
  { textEs: 'Si confesamos nuestros pecados, Dios es fiel y justo para perdonarlos.', textEn: 'If we confess our sins, he is faithful and just and will forgive us our sins.', referenceEs: '1 Juan 1:9', referenceEn: '1 John 1:9' },
  { textEs: 'Miren cuánto amor nos ha dado el Padre, que se nos llame hijos de Dios.', textEn: 'See what great love the Father has lavished on us, that we should be called children of God!', referenceEs: '1 Juan 3:1', referenceEn: '1 John 3:1' },
  { textEs: 'No amemos de palabra ni de labios para afuera, sino con hechos y de verdad.', textEn: 'Let us not love with words or speech but with actions and in truth.', referenceEs: '1 Juan 3:18', referenceEn: '1 John 3:18' },
  { textEs: 'En el amor no hay temor, sino que el amor perfecto echa fuera el temor.', textEn: 'There is no fear in love. But perfect love drives out fear.', referenceEs: '1 Juan 4:18', referenceEn: '1 John 4:18' },
  { textEs: 'Nosotros amamos porque él nos amó primero.', textEn: 'We love because he first loved us.', referenceEs: '1 Juan 4:19', referenceEn: '1 John 4:19' },
  { textEs: 'Dios es amor. El que permanece en amor permanece en Dios.', textEn: 'God is love. Whoever lives in love lives in God, and God in them.', referenceEs: '1 Juan 4:16', referenceEn: '1 John 4:16' },
  { textEs: 'El que es fiel cumple su palabra; este es el amor de Dios.', textEn: 'This is love for God: to keep his commands. And his commands are not burdensome.', referenceEs: '1 Juan 5:3', referenceEn: '1 John 5:3' },
  { textEs: 'El que tiene al Hijo tiene la vida.', textEn: 'Whoever has the Son has life.', referenceEs: '1 Juan 5:12', referenceEn: '1 John 5:12' },
  { textEs: 'El mundo se acaba con sus malos deseos, pero el que hace la voluntad de Dios permanece para siempre.', textEn: 'The world and its desires pass away, but whoever does the will of God lives forever.', referenceEs: '1 Juan 2:17', referenceEn: '1 John 2:17' },
  // — 3 Juan / 3 John —
  { textEs: 'Querido hermano, oro para que te vaya bien en todo y que tengas buena salud.', textEn: 'Dear friend, I pray that you may enjoy good health and that all may go well with you.', referenceEs: '3 Juan 1:2', referenceEn: '3 John 1:2' },
  // — Judas / Jude —
  { textEs: 'Manténganse en el amor de Dios, esperando la misericordia de nuestro Señor Jesucristo.', textEn: 'Keep yourselves in God’s love as you wait for the mercy of our Lord Jesus Christ.', referenceEs: 'Judas 1:21', referenceEn: 'Jude 1:21' },
  // — Apocalipsis / Revelation —
  { textEs: 'Yo soy el Alfa y la Omega, el principio y el fin.', textEn: 'I am the Alpha and the Omega, the Beginning and the End.', referenceEs: 'Apocalipsis 21:6', referenceEn: 'Revelation 21:6' },
  { textEs: 'Él les enjugará toda lágrima de los ojos. Ya no habrá muerte ni llanto.', textEn: 'He will wipe every tear from their eyes. There will be no more death or mourning.', referenceEs: 'Apocalipsis 21:4', referenceEn: 'Revelation 21:4' },
  { textEs: 'Mira que estoy a la puerta y llamo. Si alguno oye mi voz y abre la puerta, entraré.', textEn: 'Here I am! I stand at the door and knock. If anyone hears my voice and opens the door, I will come in.', referenceEs: 'Apocalipsis 3:20', referenceEn: 'Revelation 3:20' },
  { textEs: '¡Yo hago nuevas todas las cosas!', textEn: 'I am making everything new!', referenceEs: 'Apocalipsis 21:5', referenceEn: 'Revelation 21:5' },
  { textEs: 'Sé fiel hasta la muerte, y yo te daré la corona de la vida.', textEn: 'Be faithful, even to the point of death, and I will give you life as your victor’s crown.', referenceEs: 'Apocalipsis 2:10', referenceEn: 'Revelation 2:10' },
  { textEs: 'Digno eres, Señor y Dios nuestro, de recibir la gloria, la honra y el poder.', textEn: 'You are worthy, our Lord and God, to receive glory and honor and power.', referenceEs: 'Apocalipsis 4:11', referenceEn: 'Revelation 4:11' },
  { textEs: 'El que tenga sed, venga; y el que quiera, tome gratuitamente del agua de la vida.', textEn: 'Let the one who is thirsty come; and let the one who wishes take the free gift of the water of life.', referenceEs: 'Apocalipsis 22:17', referenceEn: 'Revelation 22:17' }
];

export function getDailyVerse(date: Date = new Date()): Verse {
  const start = new Date(date.getFullYear(), 0, 0);
  const diff = date.getTime() - start.getTime();
  const dayOfYear = Math.floor(diff / (1000 * 60 * 60 * 24));
  return verses[dayOfYear % verses.length];
}
